[default]
# No default information is currently defined.

[development]
# Enable the Flask debug mode
flask_debug = true
extensions = ["flask_debugtoolbar:DebugToolbarExtension"]
debug_tb_enabled = true
debug_tb_intercept_redirects = false
logging_level = "DEBUG"
sqlalchemy_echo = false

[production]
# Disables the Flask debug mode
flask_debug = false
logging_level = "INFO"
sqlalchemy_echo = false
